name: Update Current Affairs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Last automatic update: $(date -u)" > update-time.txt

      - name: Save update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add update-time.txt
          git diff --cached --quiet || git commit -m "Update current affairs"
          git push